osx_image: xcode10.2
language: swift
xcode_sdk: iphonesimulator10.2
podfile: path/to/Podfile
notifications:
  slack: eskaria:RRTsJOW40z95SajyTLBy7lxy
script:
- set -o pipefail && pod install && xcodebuild test -project AstrologyCalc.xcworkspace -scheme AstrologyCalcTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7' ONLY_ACTIVE_ARCH=NO | xcpretty -c --test --color
